version: '2.1'
services:
  web:
    image: exp-flask
    build: ./build-scripts
    container_name: exp-web
    restart: always
    ports:
      - 5001:5001
    volumes:
      - .:/expression-flask
    extra_hosts:
      - "redis-server.expression.hosts:192.168.0.4"
      - "mongo-server.expression.hosts:192.168.0.4"
      - "flask-server.expression.hosts:192.168.0.4"
    sysctls:
      - net.ipv4.tcp_keepalive_time=1800
      - net.ipv4.tcp_keepalive_probes=3
      - net.ipv4.tcp_keepalive_intvl=15
      - net.ipv4.tcp_max_tw_buckets=25000
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.tcp_fin_timeout=10
      - net.ipv4.tcp_syncookies=0
      - net.core.somaxconn=65535

  flower:
    image: exp-flask
    container_name: exp-flower
    restart: always
    ports:
      - 50082:5555
    volumes:
      - .:/expression-flask
    extra_hosts:
      - "redis-server.expression.hosts:192.168.0.4"
      - "mongo-server.expression.hosts:192.168.0.4"
      - "flask-server.expression.hosts:192.168.0.4"
    entrypoint: celery flower -A app.async_tasks.celery_config.app --address=0.0.0.0 --port=5555

  nginx:
    image: nginx:stable
    container_name: exp-nginx
    restart: always
    network_mode: "host"
    volumes:
      - ./build-scripts/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build-scripts/nginx/conf.d:/etc/nginx/conf.d
      # 证书不要放在代码仓库中
      - /root/expression/nginx/cert:/etc/nginx/cert
      # 挂载日志路径
      - ./log/nginx:/var/log/nginx
      # 挂入静态文件
      - /root/expression/expression-vue/dist:/var/www/expression-vue/dist
      - /root/expression/expression-wx-static:/var/www/expression-wx-static
